version: '3.8'
services:
  db:
    container_name: postgres_server
    image: 'postgres:16'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: dbdesafio_caju
    ports:
      - "5432:5432"
    networks:
      - desafio-network
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
  pgadmin:
    container_name: PgAdmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adrianoaguiardez@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "8081:80"
    networks:
      - desafio-network
  api:
    image: desafio-api
    build: .
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_server:5432/dbdesafio_caju
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345678
    ports:
      - 8080:8080
    networks:
      - desafio-network
    container_name: desafio-api
networks:
  desafio-network:
    driver: bridge